package teamfour.tasc.model.task.exceptions;

/**
 * If the task is already completed, but we try to mark it as complete again.
 */
public class TaskAlreadyCompletedException extends Exception {

}
